spring:
  application:
    name: tlias-web

  #配置数据库连接信息
  datasource:
#    url: jdbc:mysql://192.168.100.128:3306/tlias
    url: jdbc:mysql://localhost:3306/tlias
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB

#mybatis相关配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰命名映射开关
    map-underscore-to-camel-case: true

aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: happpy-java-ai
    region: cn-beijing


